env: struct_sarl

env_args:
  components: 2
  state_config: obs
  discount_reward: 0.95
  k_comp: None

learner_log_interval: 10000
log_interval: 10000
runner_log_interval: 10000
test_interval: 10000
test_nepisode: 30
test_greedy: True
t_max: 1000000
